services:
    db:
        image: postgres:10-alpine
        container_name: unleash-db
        expose:
            - "5432"
        environment:
            POSTGRES_DB: "db"
            POSTGRES_HOST_AUTH_METHOD: "trust"
        healthcheck:
            test: ["CMD", "pg_isready", "--username=postgres", "--host=127.0.0.1", "--port=5432"]

    web:
        image: unleashorg/unleash-server:4.0.5-node14-alpine
        container_name: unleash-web
        ports:
            - "4242:4242"
        environment:
            DATABASE_URL: "postgres://postgres:unleash@db/postgres"
            DATABASE_SSL: "false"
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "nc",  "-z", "db", "5432"]

    sample:
        image: unleash-sample
        container_name: unleash-sample
        build:
            context: ./src/
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        depends_on:
            web:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl",  "--fail", "http://localhost:80/health"]

