services:
    app-config-sample:
        image: app-config-sample
        container_name: app-config-sample
        build:
            context: ./src/
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        environment:
            - APP_CONFIG="<APP_CONFIG_CONNECTION_STRING>"
        healthcheck:
            test: ["CMD", "curl",  "--fail", "http://localhost:80/health"]

